global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'admin'
    static_configs:
      - targets: ['admin:8040']
